2025-04-19 09:53:51.597 | INFO     | app.services.ingredient:search_ingredients:36 - Searching ingredients with query: chicken
2025-04-19 09:53:51.623 | INFO     | app.services.ingredient:search_ingredients:36 - Searching ingredients with query: nonexistent
2025-04-19 09:53:51.647 | INFO     | app.services.ingredient:search_ingredients:36 - Searching ingredients with query: chicken
2025-04-19 10:05:01.131 | ERROR    | app.main:global_exception_handler:31 - Unhandled exception: 1 validation errors:
  {'type': 'missing', 'loc': ('response', '_id'), 'msg': 'Field required', 'input': {'name': 'Chicken Breast', 'description': 'Boneless, skinless chicken breast', 'quantity': 100.0, 'unit': 1.0, 'reference_quantity': 100.0, 'reference_unit': 'g', 'nutrients': {'protein': 31.0, 'fat': 3.6, 'carbohydrates': 0.0, 'calories': 165.0}, 'id': '507f1f77bcf86cd799439011'}}

Traceback (most recent call last):

  File "C:\Program Files\Python310\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002C5304AD990>
    └ <Thread(Thread-1 (run_blocking_portal), started daemon 4088)>

  File "C:\Program Files\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002C5304AD6C0>
    └ <Thread(Thread-1 (run_blocking_portal), started daemon 4088)>

  File "C:\Program Files\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1 (run_blocking_portal), started daemon 4088)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-1 (run_blocking_portal), started daemon 4088)>
    │    └ <function start_blocking_portal.<locals>.run_blocking_portal at 0x000002C53439D360>
    └ <Thread(Thread-1 (run_blocking_portal), started daemon 4088)>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\anyio\from_thread.py", line 481, in run_blocking_portal
    _eventloop.run(
    │          └ <function run at 0x000002C530D88DC0>
    └ <module 'anyio._core._eventloop' from 'C:\\Users\\ELITE SPACE FOOTBALL\\Documents\\mock_server\\.mock_server\\lib\\site-packa...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\anyio\_core\_eventloop.py", line 74, in run
    return async_backend.run(func, args, {}, backend_options)
           │             │   │     │         └ {}
           │             │   │     └ ()
           │             │   └ <function start_blocking_portal.<locals>.run_portal at 0x000002C53439CEE0>
           │             └ <classmethod(<function AsyncIOBackend.run at 0x000002C534439000>)>
           └ <class 'anyio._backends._asyncio.AsyncIOBackend'>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\anyio\_backends\_asyncio.py", line 2310, in run
    return runner.run(wrapper())
           │      │   └ <function start_blocking_portal.<locals>.run_portal at 0x000002C53439D480>
           │      └ <function Runner.run at 0x000002C53439ECB0>
           └ <anyio._backends._asyncio.Runner object at 0x000002C5343DAB90>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\anyio\_backends\_asyncio.py", line 217, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='anyio.from_thread.start_blocking_portal.<locals>.run_portal' coro=<start_blocking_portal.<locals>.run_por...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x000002C5327393F0>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <anyio._backends._asyncio.Runner object at 0x000002C5343DAB90>

  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000002C53278F7F0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Program Files\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()

  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000002C53273AE60>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000002C530EEA830>
    └ <Handle Task.task_wakeup(<Future finis...al_tracker'))>)>

  File "C:\Program Files\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finis...al_tracker'))>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finis...al_tracker'))>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finis...al_tracker'))>)>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\anyio\from_thread.py", line 221, in _call_func
    retval = await retval_or_awaitable
                   └ <coroutine object FastAPI.__call__ at 0x000002C5344090E0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <function _TestClientTransport.handle_request.<locals>.send at 0x000002C5342C6C20>
                           │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x000002C534301900>
                           └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/ingredients/', 'raw_path': b'/api/v1/ingredients/'...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <function _TestClientTransport.handle_request.<locals>.send at 0x000002C5342C6C20>
          │    │                │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x000002C534301900>
          │    │                └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/ingredients/', 'raw_path': b'/api/v1/ingredients/'...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x000002C53442DE40>
          └ <fastapi.applications.FastAPI object at 0x000002C533A537C0>

> File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x000002C53443A710>
          │    │   │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x000002C534301900>
          │    │   └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/ingredients/', 'raw_path': b'/api/v1/ingredients/'...
          │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x000002C53442DF00>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x000002C53442DE40>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
          │                            │    │    │     │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x000002C53443A710>
          │                            │    │    │     │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x000002C534301900>
          │                            │    │    │     └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/ingredients/', 'raw_path': b'/api/v1/ingredients/'...
          │                            │    │    └ <starlette.requests.Request object at 0x000002C53442E0B0>
          │                            │    └ <fastapi.routing.APIRouter object at 0x000002C534368460>
          │                            └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x000002C53442DF00>
          └ <function wrap_app_handling_exceptions at 0x000002C5337A31C0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000002C53443A7A0>
          │   │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x000002C534301900>
          │   └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/ingredients/', 'raw_path': b'/api/v1/ingredients/'...
          └ <fastapi.routing.APIRouter object at 0x000002C534368460>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000002C53443A7A0>
          │    │                │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x000002C534301900>
          │    │                └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/ingredients/', 'raw_path': b'/api/v1/ingredients/'...
          │    └ <bound method Router.app of <fastapi.routing.APIRouter object at 0x000002C534368460>>
          └ <fastapi.routing.APIRouter object at 0x000002C534368460>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000002C53443A7A0>
          │     │      │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x000002C534301900>
          │     │      └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/ingredients/', 'raw_path': b'/api/v1/ingredients/'...
          │     └ <function Route.handle at 0x000002C5337C0700>
          └ APIRoute(path='/api/v1/ingredients/', name='create_new_ingredient', methods=['POST'])

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000002C53443A7A0>
          │    │   │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x000002C534301900>
          │    │   └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/ingredients/', 'raw_path': b'/api/v1/ingredients/'...
          │    └ <function request_response.<locals>.app at 0x000002C53431FE20>
          └ APIRoute(path='/api/v1/ingredients/', name='create_new_ingredient', methods=['POST'])

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
          │                            │    │        │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000002C53443A7A0>
          │                            │    │        │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x000002C534301900>
          │                            │    │        └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/ingredients/', 'raw_path': b'/api/v1/ingredients/'...
          │                            │    └ <starlette.requests.Request object at 0x000002C53442DC90>
          │                            └ <function request_response.<locals>.app.<locals>.app at 0x000002C53443A830>
          └ <function wrap_app_handling_exceptions at 0x000002C5337A31C0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000002C53443A8C0>
          │   │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x000002C534301900>
          │   └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/ingredients/', 'raw_path': b'/api/v1/ingredients/'...
          └ <function request_response.<locals>.app.<locals>.app at 0x000002C53443A830>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
                     │ └ <starlette.requests.Request object at 0x000002C53442DC90>
                     └ <function get_request_handler.<locals>.app at 0x000002C53431FD90>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\fastapi\routing.py", line 327, in app
    content = await serialize_response(
                    └ <function serialize_response at 0x000002C5337C15A0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\fastapi\routing.py", line 176, in serialize_response
    raise ResponseValidationError(
          └ <class 'fastapi.exceptions.ResponseValidationError'>

fastapi.exceptions.ResponseValidationError: 1 validation errors:
  {'type': 'missing', 'loc': ('response', '_id'), 'msg': 'Field required', 'input': {'name': 'Chicken Breast', 'description': 'Boneless, skinless chicken breast', 'quantity': 100.0, 'unit': 1.0, 'reference_quantity': 100.0, 'reference_unit': 'g', 'nutrients': {'protein': 31.0, 'fat': 3.6, 'carbohydrates': 0.0, 'calories': 165.0}, 'id': '507f1f77bcf86cd799439011'}}

2025-04-19 10:05:01.825 | INFO     | app.services.ingredient:search_ingredients:81 - Searching ingredients with query: chicken
2025-04-19 10:05:01.841 | INFO     | app.services.ingredient:search_ingredients:81 - Searching ingredients with query: nonexistent
2025-04-19 10:05:01.858 | INFO     | app.services.ingredient:search_ingredients:81 - Searching ingredients with query: chicken
2025-04-19 10:13:43.997 | ERROR    | app.main:global_exception_handler:31 - Unhandled exception: 1 validation error for Ingredient
_id
  Field required [type=missing, input_value={'id': '507f1f77bcf86cd79...0.0, 'calories': 165.0}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
Traceback (most recent call last):

  File "C:\Program Files\Python310\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x00000258FF79D990>
    └ <Thread(Thread-1 (run_blocking_portal), started daemon 15216)>

  File "C:\Program Files\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x00000258FF79D6C0>
    └ <Thread(Thread-1 (run_blocking_portal), started daemon 15216)>

  File "C:\Program Files\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1 (run_blocking_portal), started daemon 15216)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-1 (run_blocking_portal), started daemon 15216)>
    │    └ <function start_blocking_portal.<locals>.run_blocking_portal at 0x00000258835CD2D0>
    └ <Thread(Thread-1 (run_blocking_portal), started daemon 15216)>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\anyio\from_thread.py", line 481, in run_blocking_portal
    _eventloop.run(
    │          └ <function run at 0x0000025880058DC0>
    └ <module 'anyio._core._eventloop' from 'C:\\Users\\ELITE SPACE FOOTBALL\\Documents\\mock_server\\.mock_server\\lib\\site-packa...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\anyio\_core\_eventloop.py", line 74, in run
    return async_backend.run(func, args, {}, backend_options)
           │             │   │     │         └ {}
           │             │   │     └ ()
           │             │   └ <function start_blocking_portal.<locals>.run_portal at 0x00000258835CCE50>
           │             └ <classmethod(<function AsyncIOBackend.run at 0x0000025883668F70>)>
           └ <class 'anyio._backends._asyncio.AsyncIOBackend'>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\anyio\_backends\_asyncio.py", line 2310, in run
    return runner.run(wrapper())
           │      │   └ <function start_blocking_portal.<locals>.run_portal at 0x00000258835CD3F0>
           │      └ <function Runner.run at 0x00000258835CEC20>
           └ <anyio._backends._asyncio.Runner object at 0x000002588360B220>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\anyio\_backends\_asyncio.py", line 217, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='anyio.from_thread.start_blocking_portal.<locals>.run_portal' coro=<start_blocking_portal.<locals>.run_por...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x00000258819D93F0>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <anyio._backends._asyncio.Runner object at 0x000002588360B220>

  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x0000025881A2F7F0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Program Files\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()

  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x00000258819DAE60>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x00000258801BA830>
    └ <Handle Task.task_wakeup(<Future finis...al_tracker'))>)>

  File "C:\Program Files\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finis...al_tracker'))>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finis...al_tracker'))>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finis...al_tracker'))>)>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\anyio\from_thread.py", line 221, in _call_func
    retval = await retval_or_awaitable
                   └ <coroutine object FastAPI.__call__ at 0x00000258836354D0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <function _TestClientTransport.handle_request.<locals>.send at 0x00000258834F6C20>
                           │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x0000025883531900>
                           └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/ingredients/', 'raw_path': b'/api/v1/ingredients/'...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <function _TestClientTransport.handle_request.<locals>.send at 0x00000258834F6C20>
          │    │                │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x0000025883531900>
          │    │                └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/ingredients/', 'raw_path': b'/api/v1/ingredients/'...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x000002588365A230>
          └ <fastapi.applications.FastAPI object at 0x0000025882CB38E0>

> File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x000002588366A680>
          │    │   │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x0000025883531900>
          │    │   └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/ingredients/', 'raw_path': b'/api/v1/ingredients/'...
          │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x000002588365A2F0>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x000002588365A230>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
          │                            │    │    │     │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x000002588366A680>
          │                            │    │    │     │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x0000025883531900>
          │                            │    │    │     └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/ingredients/', 'raw_path': b'/api/v1/ingredients/'...
          │                            │    │    └ <starlette.requests.Request object at 0x000002588365A4A0>
          │                            │    └ <fastapi.routing.APIRouter object at 0x0000025883570850>
          │                            └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x000002588365A2F0>
          └ <function wrap_app_handling_exceptions at 0x0000025882A031C0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000002588366A710>
          │   │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x0000025883531900>
          │   └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/ingredients/', 'raw_path': b'/api/v1/ingredients/'...
          └ <fastapi.routing.APIRouter object at 0x0000025883570850>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000002588366A710>
          │    │                │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x0000025883531900>
          │    │                └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/ingredients/', 'raw_path': b'/api/v1/ingredients/'...
          │    └ <bound method Router.app of <fastapi.routing.APIRouter object at 0x0000025883570850>>
          └ <fastapi.routing.APIRouter object at 0x0000025883570850>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000002588366A710>
          │     │      │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x0000025883531900>
          │     │      └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/ingredients/', 'raw_path': b'/api/v1/ingredients/'...
          │     └ <function Route.handle at 0x0000025882A20700>
          └ APIRoute(path='/api/v1/ingredients/', name='create_new_ingredient', methods=['POST'])

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000002588366A710>
          │    │   │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x0000025883531900>
          │    │   └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/ingredients/', 'raw_path': b'/api/v1/ingredients/'...
          │    └ <function request_response.<locals>.app at 0x000002588354FD90>
          └ APIRoute(path='/api/v1/ingredients/', name='create_new_ingredient', methods=['POST'])

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
          │                            │    │        │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000002588366A710>
          │                            │    │        │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x0000025883531900>
          │                            │    │        └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/ingredients/', 'raw_path': b'/api/v1/ingredients/'...
          │                            │    └ <starlette.requests.Request object at 0x000002588365A080>
          │                            └ <function request_response.<locals>.app.<locals>.app at 0x000002588366A7A0>
          └ <function wrap_app_handling_exceptions at 0x0000025882A031C0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000002588366A830>
          │   │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x0000025883531900>
          │   └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/ingredients/', 'raw_path': b'/api/v1/ingredients/'...
          └ <function request_response.<locals>.app.<locals>.app at 0x000002588366A7A0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
                     │ └ <starlette.requests.Request object at 0x000002588365A080>
                     └ <function get_request_handler.<locals>.app at 0x000002588354FD00>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x0000025882A22200>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {'user_id': 'test_user_id', 'db': AsyncIOMotorDatabase(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz...
                 │         └ <function create_new_ingredient at 0x000002588354E200>
                 └ Dependant(path_params=[], query_params=[], header_params=[], cookie_params=[], body_params=[ModelField(field_info=Body(Pydant...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\api\v1\ingredient.py", line 32, in create_new_ingredient
    return await create_ingredient(db, ingredient)
                 │                 │   └ IngredientCreate(name='Chicken Breast', description='Boneless, skinless chicken breast', quantity=100.0, unit=1.0, reference_...
                 │                 └ AsyncIOMotorDatabase(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False, drive...
                 └ <function create_ingredient at 0x000002588354DCF0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\services\ingredient.py", line 35, in create_ingredient
    ingredient = Ingredient(id=str(ingredient_id), **ingredient_dict)
                 │                 │                 └ {'name': 'Chicken Breast', 'description': 'Boneless, skinless chicken breast', 'quantity': 100.0, 'unit': 1.0, 'reference_qua...
                 │                 └ ObjectId('507f1f77bcf86cd799439011')
                 └ <class 'app.models.ingredient.Ingredient'>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\pydantic\main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     │    │                      │               │                   └ Ingredient()
                     │    │                      │               └ {'id': '507f1f77bcf86cd799439011', 'name': 'Chicken Breast', 'description': 'Boneless, skinless chicken breast', 'quantity': ...
                     │    │                      └ <method 'validate_python' of 'pydantic_core._pydantic_core.SchemaValidator' objects>
                     │    └ SchemaValidator(title="Ingredient", validator=Model(
                     │          ModelValidator {
                     │              revalidate: Never,
                     │              validator: Model...
                     └ Ingredient()

pydantic_core._pydantic_core.ValidationError: 1 validation error for Ingredient
_id
  Field required [type=missing, input_value={'id': '507f1f77bcf86cd79...0.0, 'calories': 165.0}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-04-19 10:13:44.696 | INFO     | app.services.ingredient:search_ingredients:77 - Searching ingredients with query: chicken
2025-04-19 10:13:44.712 | INFO     | app.services.ingredient:search_ingredients:77 - Searching ingredients with query: nonexistent
2025-04-19 10:13:44.729 | INFO     | app.services.ingredient:search_ingredients:77 - Searching ingredients with query: chicken
