2025-04-12 17:54:16.225 | INFO     | __main__:lifespan:15 - Application startup completed
2025-04-12 17:54:26.478 | ERROR    | __main__:global_exception_handler:28 - Unhandled exception: You must call FastAPILimiter.init in startup event of fastapi!
Traceback (most recent call last):

  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': None, '__package__': 'app', '__loader__': <_frozen_importlib_external.SourceFileLoader ob...
           │         └ <code object <module> at 0x000001FC3DF028C0, file "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\main.py", line 1>
           └ <function _run_code at 0x000001FC3DB1A4D0>

  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': None, '__package__': 'app', '__loader__': <_frozen_importlib_external.SourceFileLoader ob...
         └ <code object <module> at 0x000001FC3DF028C0, file "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\main.py", line 1>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\main.py", line 40, in <module>
    uvicorn.run(app, host="0.0.0.0", port=8000)
    │       │   └ <fastapi.applications.FastAPI object at 0x000001FC3DB6EE00>
    │       └ <function run at 0x000001FC41DA3370>
    └ <module 'uvicorn' from 'C:\\Users\\ELITE SPACE FOOTBALL\\Documents\\mock_server\\.mock_server\\lib\\site-packages\\uvicorn\\_...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\uvicorn\main.py", line 579, in run
    server.run()
    │      └ <function Server.run at 0x000001FC41DA2CB0>
    └ <uvicorn.server.Server object at 0x000001FC41DE15A0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\uvicorn\server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x000001FC41DA2D40>
           │       │   └ <uvicorn.server.Server object at 0x000001FC41DE15A0>
           │       └ <function run at 0x000001FC3DF8B880>
           └ <module 'asyncio' from 'C:\\Program Files\\Python310\\lib\\asyncio\\__init__.py'>

  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x000001FC41D778B0>
           │    └ <function BaseEventLoop.run_until_complete at 0x000001FC3FBB2050>
           └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000001FC3FC61CF0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Program Files\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()

  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000001FC3FBB3AC0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000001FC3FB47490>
    └ <Handle <TaskStepMethWrapper object at 0x000001FC41E51D20>()>

  File "C:\Program Files\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x000001FC41E51D20>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x000001FC41E51D20>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x000001FC41E51D20>()>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x000001FC41DE1E10>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001FC41E51CC0>>
                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001FC41E51...
                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
                 │    └ <fastapi.applications.FastAPI object at 0x000001FC3DB6EE00>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x000001FC41DE1E10>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001FC41E51CC0>>
                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001FC41E51...
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001FC41E51CC0>>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001FC41E51...
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x000001FC41E50BE0>
          └ <fastapi.applications.FastAPI object at 0x000001FC3DB6EE00>

> File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x000001FC41E64820>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001FC41E51...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x000001FC41E50BB0>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x000001FC41E50BE0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
          │                            │    │    │     │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x000001FC41E64820>
          │                            │    │    │     │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001FC41E51...
          │                            │    │    │     └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │                            │    │    └ <starlette.requests.Request object at 0x000001FC41E511E0>
          │                            │    └ <fastapi.routing.APIRouter object at 0x000001FC41C896C0>
          │                            └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x000001FC41E50BB0>
          └ <function wrap_app_handling_exceptions at 0x000001FC408BFAC0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001FC41E648B0>
          │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001FC41E51...
          │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          └ <fastapi.routing.APIRouter object at 0x000001FC41C896C0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001FC41E648B0>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001FC41E51...
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <bound method Router.app of <fastapi.routing.APIRouter object at 0x000001FC41C896C0>>
          └ <fastapi.routing.APIRouter object at 0x000001FC41C896C0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001FC41E648B0>
          │     │      │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001FC41E51...
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │     └ <function Route.handle at 0x000001FC408E9000>
          └ APIRoute(path='/api/v1/users/register', name='register', methods=['POST'])

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001FC41E648B0>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001FC41E51...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <function request_response.<locals>.app at 0x000001FC41C77D90>
          └ APIRoute(path='/api/v1/users/register', name='register', methods=['POST'])

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
          │                            │    │        │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001FC41E648B0>
          │                            │    │        │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001FC41E51...
          │                            │    │        └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │                            │    └ <starlette.requests.Request object at 0x000001FC41E51810>
          │                            └ <function request_response.<locals>.app.<locals>.app at 0x000001FC41E64940>
          └ <function wrap_app_handling_exceptions at 0x000001FC408BFAC0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001FC41E649D0>
          │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001FC41E51...
          │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          └ <function request_response.<locals>.app.<locals>.app at 0x000001FC41E64940>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
                     │ └ <starlette.requests.Request object at 0x000001FC41E51810>
                     └ <function get_request_handler.<locals>.app at 0x000001FC41C77AC0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\fastapi\routing.py", line 291, in app
    solved_result = await solve_dependencies(
                          └ <function solve_dependencies at 0x000001FC408BD120>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\fastapi\dependencies\utils.py", line 638, in solve_dependencies
    solved = await call(**solved_result.values)
                   │      │             └ {'request': <starlette.requests.Request object at 0x000001FC41E51810>, 'response': <starlette.responses.Response object at 0x...
                   │      └ SolvedDependency(values={'request': <starlette.requests.Request object at 0x000001FC41E51810>, 'response': <starlette.respons...
                   └ <fastapi_limiter.depends.RateLimiter object at 0x000001FC411A0970>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\fastapi_limiter\depends.py", line 37, in __call__
    raise Exception("You must call FastAPILimiter.init in startup event of fastapi!")

Exception: You must call FastAPILimiter.init in startup event of fastapi!
2025-04-12 18:06:22.859 | INFO     | __main__:lifespan:15 - Application startup completed
2025-04-12 18:06:29.276 | INFO     | app.api.v1.user:register:12 - Registering user: sammyscarface
2025-04-12 18:06:34.879 | INFO     | app.services.user:register_user:12 - User registered: sammyscarface
2025-04-12 18:10:01.236 | INFO     | app.services.user:login_user:21 - User logged in: sammyscarface
2025-04-12 18:58:50.982 | INFO     | app.services.user:login_user:21 - User logged in: sammyscarface
2025-04-12 19:15:40.511 | INFO     | app.services.user:login_user:21 - User logged in: sammyscarface
2025-04-12 19:20:25.646 | INFO     | app.services.user:login_user:21 - User logged in: sammyscarface
2025-04-12 19:21:10.968 | INFO     | app.services.meal:create_meal_entry:9 - Meal created by user 67fa8f895a7f4e0712d33d9b: Fio Fio
2025-04-12 19:31:19.873 | INFO     | __main__:lifespan:20 - Application shutdown completed
2025-04-13 12:59:23.404 | INFO     | __main__:lifespan:15 - Application startup completed
2025-04-13 13:06:56.779 | INFO     | app.services.user:login_user:21 - User logged in: sammyscarface
2025-04-13 13:35:43.433 | INFO     | app.services.user:login_user:21 - User logged in: sammyscarface
2025-04-13 13:44:36.308 | WARNING  | app.services.user:login_user:18 - Login failed for username: sammyscarface
2025-04-13 13:44:45.150 | WARNING  | app.services.user:login_user:18 - Login failed for username: sammyscarface
2025-04-13 13:45:19.059 | WARNING  | app.services.user:login_user:18 - Login failed for username: sammyscarface
2025-04-13 13:46:53.159 | INFO     | app.services.user:login_user:21 - User logged in: sammyscarface
2025-04-13 13:49:31.666 | INFO     | __main__:lifespan:15 - Application startup completed
2025-04-13 13:50:26.235 | INFO     | app.services.user:login_user:21 - User logged in: sammyscarface
2025-04-13 13:50:26.259 | ERROR    | __main__:global_exception_handler:28 - Unhandled exception: maximum recursion depth exceeded
Traceback (most recent call last):

  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': None, '__package__': 'app', '__loader__': <_frozen_importlib_external.SourceFileLoader ob...
           │         └ <code object <module> at 0x000001CC4BB8E970, file "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\main.py", line 1>
           └ <function _run_code at 0x000001CC4BB9A4D0>

  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': None, '__package__': 'app', '__loader__': <_frozen_importlib_external.SourceFileLoader ob...
         └ <code object <module> at 0x000001CC4BB8E970, file "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\main.py", line 1>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\main.py", line 40, in <module>
    uvicorn.run(app, host="0.0.0.0", port=8000)
    │       │   └ <fastapi.applications.FastAPI object at 0x000001CC4BB7BD30>
    │       └ <function run at 0x000001CC4FE0F490>
    └ <module 'uvicorn' from 'C:\\Users\\ELITE SPACE FOOTBALL\\Documents\\mock_server\\.mock_server\\lib\\site-packages\\uvicorn\\_...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\uvicorn\main.py", line 579, in run
    server.run()
    │      └ <function Server.run at 0x000001CC4FE0EDD0>
    └ <uvicorn.server.Server object at 0x000001CC4FE4DBA0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\uvicorn\server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x000001CC4FE0EE60>
           │       │   └ <uvicorn.server.Server object at 0x000001CC4FE4DBA0>
           │       └ <function run at 0x000001CC4BFEF6D0>
           └ <module 'asyncio' from 'C:\\Program Files\\Python310\\lib\\asyncio\\__init__.py'>

  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x000001CC4FDE7840>
           │    └ <function BaseEventLoop.run_until_complete at 0x000001CC4DC22050>
           └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000001CC4DCD1CF0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Program Files\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()

  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000001CC4DC23AC0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000001CC4DBB7490>
    └ <Handle Task.task_wakeup(<Future finis...al_tracker'))>)>

  File "C:\Program Files\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finis...al_tracker'))>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finis...al_tracker'))>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finis...al_tracker'))>)>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x000001CC4FE4E410>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001CC4FF1BEE0>>
                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001CC4FF1B...
                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
                 │    └ <fastapi.applications.FastAPI object at 0x000001CC4BB7BD30>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x000001CC4FE4E410>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001CC4FF1BEE0>>
                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001CC4FF1B...
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001CC4FF1BEE0>>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001CC4FF1B...
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x000001CC4FED11E0>
          └ <fastapi.applications.FastAPI object at 0x000001CC4BB7BD30>

> File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x000001CC4FED4700>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001CC4FF1B...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x000001CC4FED11B0>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x000001CC4FED11E0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
          │                            │    │    │     │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x000001CC4FED4700>
          │                            │    │    │     │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001CC4FF1B...
          │                            │    │    │     └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │                            │    │    └ <starlette.requests.Request object at 0x000001CC4FF1AC80>
          │                            │    └ <fastapi.routing.APIRouter object at 0x000001CC4F210850>
          │                            └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x000001CC4FED11B0>
          └ <function wrap_app_handling_exceptions at 0x000001CC4E92FAC0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001CC4FED4670>
          │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001CC4FF1B...
          │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          └ <fastapi.routing.APIRouter object at 0x000001CC4F210850>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001CC4FED4670>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001CC4FF1B...
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <bound method Router.app of <fastapi.routing.APIRouter object at 0x000001CC4F210850>>
          └ <fastapi.routing.APIRouter object at 0x000001CC4F210850>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001CC4FED4670>
          │     │      │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001CC4FF1B...
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │     └ <function Route.handle at 0x000001CC4E959000>
          └ APIRoute(path='/api/v1/meals/last', name='get_last_meal_by_user', methods=['GET'])

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001CC4FED4670>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001CC4FF1B...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <function request_response.<locals>.app at 0x000001CC4FD28280>
          └ APIRoute(path='/api/v1/meals/last', name='get_last_meal_by_user', methods=['GET'])

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
          │                            │    │        │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001CC4FED4670>
          │                            │    │        │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001CC4FF1B...
          │                            │    │        └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │                            │    └ <starlette.requests.Request object at 0x000001CC4FF1A740>
          │                            └ <function request_response.<locals>.app.<locals>.app at 0x000001CC50040550>
          └ <function wrap_app_handling_exceptions at 0x000001CC4E92FAC0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001CC50040670>
          │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001CC4FF1B...
          │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          └ <function request_response.<locals>.app.<locals>.app at 0x000001CC50040550>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
                     │ └ <starlette.requests.Request object at 0x000001CC4FF1A740>
                     └ <function get_request_handler.<locals>.app at 0x000001CC4FD28310>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x000001CC4E95AB00>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {'user_id': '67fa8f895a7f4e0712d33d9b', 'db': AsyncIOMotorDatabase(Database(MongoClient(host=['localhost:27017'], document_cl...
                 │         └ <function get_last_meal_by_user at 0x000001CC4FCE6EF0>
                 └ Dependant(path_params=[], query_params=[], header_params=[], cookie_params=[], body_params=[], dependencies=[Dependant(path_p...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\api\v1\meal.py", line 16, in get_last_meal_by_user
    return await get_last_meal_by_user(db, user_id)
                 │                     │   └ '67fa8f895a7f4e0712d33d9b'
                 │                     └ AsyncIOMotorDatabase(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False, drive...
                 └ <function get_last_meal_by_user at 0x000001CC4FCE6EF0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\api\v1\meal.py", line 16, in get_last_meal_by_user
    return await get_last_meal_by_user(db, user_id)
                 │                     │   └ AsyncIOMotorDatabase(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False, drive...
                 │                     └ '67fa8f895a7f4e0712d33d9b'
                 └ <function get_last_meal_by_user at 0x000001CC4FCE6EF0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\api\v1\meal.py", line 16, in get_last_meal_by_user
    return await get_last_meal_by_user(db, user_id)
                 │                     │   └ '67fa8f895a7f4e0712d33d9b'
                 │                     └ AsyncIOMotorDatabase(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False, drive...
                 └ <function get_last_meal_by_user at 0x000001CC4FCE6EF0>
  [Previous line repeated 968 more times]

RecursionError: maximum recursion depth exceeded
2025-04-13 13:53:42.563 | INFO     | __main__:lifespan:15 - Application startup completed
2025-04-13 13:54:06.889 | ERROR    | __main__:global_exception_handler:28 - Unhandled exception: maximum recursion depth exceeded
Traceback (most recent call last):

  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': None, '__package__': 'app', '__loader__': <_frozen_importlib_external.SourceFileLoader ob...
           │         └ <code object <module> at 0x000002ABDA6AE970, file "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\main.py", line 1>
           └ <function _run_code at 0x000002ABDA6BA4D0>

  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': None, '__package__': 'app', '__loader__': <_frozen_importlib_external.SourceFileLoader ob...
         └ <code object <module> at 0x000002ABDA6AE970, file "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\main.py", line 1>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\main.py", line 40, in <module>
    uvicorn.run(app, host="0.0.0.0", port=8000)
    │       │   └ <fastapi.applications.FastAPI object at 0x000002ABDA69BD30>
    │       └ <function run at 0x000002ABDE8CF520>
    └ <module 'uvicorn' from 'C:\\Users\\ELITE SPACE FOOTBALL\\Documents\\mock_server\\.mock_server\\lib\\site-packages\\uvicorn\\_...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\uvicorn\main.py", line 579, in run
    server.run()
    │      └ <function Server.run at 0x000002ABDE8CEE60>
    └ <uvicorn.server.Server object at 0x000002ABDE90DC30>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\uvicorn\server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x000002ABDE8CEEF0>
           │       │   └ <uvicorn.server.Server object at 0x000002ABDE90DC30>
           │       └ <function run at 0x000002ABDAB0F6D0>
           └ <module 'asyncio' from 'C:\\Program Files\\Python310\\lib\\asyncio\\__init__.py'>

  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x000002ABDE8A7840>
           │    └ <function BaseEventLoop.run_until_complete at 0x000002ABDC722050>
           └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000002ABDC7D1CF0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Program Files\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()

  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000002ABDC723AC0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000002ABDC6C7490>
    └ <Handle Task.task_wakeup(<Future finis...al_tracker'))>)>

  File "C:\Program Files\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finis...al_tracker'))>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finis...al_tracker'))>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finis...al_tracker'))>)>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x000002ABDE90E4A0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000002ABDE9928F0>>
                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000002ABDE992...
                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
                 │    └ <fastapi.applications.FastAPI object at 0x000002ABDA69BD30>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x000002ABDE90E4A0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000002ABDE9928F0>>
                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000002ABDE992...
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000002ABDE9928F0>>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000002ABDE992...
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x000002ABDE991270>
          └ <fastapi.applications.FastAPI object at 0x000002ABDA69BD30>

> File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x000002ABDE9949D0>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000002ABDE992...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x000002ABDE991240>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x000002ABDE991270>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
          │                            │    │    │     │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x000002ABDE9949D0>
          │                            │    │    │     │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000002ABDE992...
          │                            │    │    │     └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │                            │    │    └ <starlette.requests.Request object at 0x000002ABDE991EA0>
          │                            │    └ <fastapi.routing.APIRouter object at 0x000002ABDE7B9060>
          │                            └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x000002ABDE991240>
          └ <function wrap_app_handling_exceptions at 0x000002ABDD3EFAC0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000002ABDE994B80>
          │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000002ABDE992...
          │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          └ <fastapi.routing.APIRouter object at 0x000002ABDE7B9060>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000002ABDE994B80>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000002ABDE992...
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <bound method Router.app of <fastapi.routing.APIRouter object at 0x000002ABDE7B9060>>
          └ <fastapi.routing.APIRouter object at 0x000002ABDE7B9060>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000002ABDE994B80>
          │     │      │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000002ABDE992...
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │     └ <function Route.handle at 0x000002ABDD419000>
          └ APIRoute(path='/api/v1/meals/last', name='get_last_meal_by_user', methods=['GET'])

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000002ABDE994B80>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000002ABDE992...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <function request_response.<locals>.app at 0x000002ABDE7E8280>
          └ APIRoute(path='/api/v1/meals/last', name='get_last_meal_by_user', methods=['GET'])

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
          │                            │    │        │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000002ABDE994B80>
          │                            │    │        │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000002ABDE992...
          │                            │    │        └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │                            │    └ <starlette.requests.Request object at 0x000002ABDE991BD0>
          │                            └ <function request_response.<locals>.app.<locals>.app at 0x000002ABDE994C10>
          └ <function wrap_app_handling_exceptions at 0x000002ABDD3EFAC0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000002ABDE994CA0>
          │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000002ABDE992...
          │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          └ <function request_response.<locals>.app.<locals>.app at 0x000002ABDE994C10>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
                     │ └ <starlette.requests.Request object at 0x000002ABDE991BD0>
                     └ <function get_request_handler.<locals>.app at 0x000002ABDE7E8310>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x000002ABDD41AB00>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {'user_id': '67fa8f895a7f4e0712d33d9b', 'db': AsyncIOMotorDatabase(Database(MongoClient(host=['localhost:27017'], document_cl...
                 │         └ <function get_last_meal_by_user at 0x000002ABDE7A6EF0>
                 └ Dependant(path_params=[], query_params=[], header_params=[], cookie_params=[], body_params=[], dependencies=[Dependant(path_p...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\api\v1\meal.py", line 16, in get_last_meal_by_user
    return await get_last_meal_by_user(db, user_id)
                 │                     │   └ '67fa8f895a7f4e0712d33d9b'
                 │                     └ AsyncIOMotorDatabase(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False, drive...
                 └ <function get_last_meal_by_user at 0x000002ABDE7A6EF0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\api\v1\meal.py", line 16, in get_last_meal_by_user
    return await get_last_meal_by_user(db, user_id)
                 │                     │   └ AsyncIOMotorDatabase(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False, drive...
                 │                     └ '67fa8f895a7f4e0712d33d9b'
                 └ <function get_last_meal_by_user at 0x000002ABDE7A6EF0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\api\v1\meal.py", line 16, in get_last_meal_by_user
    return await get_last_meal_by_user(db, user_id)
                 │                     │   └ '67fa8f895a7f4e0712d33d9b'
                 │                     └ AsyncIOMotorDatabase(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False, drive...
                 └ <function get_last_meal_by_user at 0x000002ABDE7A6EF0>
  [Previous line repeated 968 more times]

RecursionError: maximum recursion depth exceeded
2025-04-13 13:54:50.693 | INFO     | __main__:lifespan:15 - Application startup completed
2025-04-13 13:55:02.645 | ERROR    | __main__:global_exception_handler:28 - Unhandled exception: 'dict' object has no attribute 'name'
Traceback (most recent call last):

  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': None, '__package__': 'app', '__loader__': <_frozen_importlib_external.SourceFileLoader ob...
           │         └ <code object <module> at 0x000001AFC4BFE970, file "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\main.py", line 1>
           └ <function _run_code at 0x000001AFC4C0A4D0>

  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': None, '__package__': 'app', '__loader__': <_frozen_importlib_external.SourceFileLoader ob...
         └ <code object <module> at 0x000001AFC4BFE970, file "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\main.py", line 1>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\main.py", line 40, in <module>
    uvicorn.run(app, host="0.0.0.0", port=8000)
    │       │   └ <fastapi.applications.FastAPI object at 0x000001AFC4BEBD30>
    │       └ <function run at 0x000001AFC8D9F520>
    └ <module 'uvicorn' from 'C:\\Users\\ELITE SPACE FOOTBALL\\Documents\\mock_server\\.mock_server\\lib\\site-packages\\uvicorn\\_...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\uvicorn\main.py", line 579, in run
    server.run()
    │      └ <function Server.run at 0x000001AFC8D9EE60>
    └ <uvicorn.server.Server object at 0x000001AFC8DD9C00>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\uvicorn\server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x000001AFC8D9EEF0>
           │       │   └ <uvicorn.server.Server object at 0x000001AFC8DD9C00>
           │       └ <function run at 0x000001AFC505F6D0>
           └ <module 'asyncio' from 'C:\\Program Files\\Python310\\lib\\asyncio\\__init__.py'>

  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x000001AFC8D77840>
           │    └ <function BaseEventLoop.run_until_complete at 0x000001AFC6C72050>
           └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000001AFC6D21CF0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Program Files\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()

  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000001AFC6C73AC0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000001AFC6C17490>
    └ <Handle Task.task_wakeup(<Future finis...o Fio', ...}]>)>

  File "C:\Program Files\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finis...o Fio', ...}]>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finis...o Fio', ...}]>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finis...o Fio', ...}]>)>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x000001AFC8DDA470>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8E628C0>>
                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8E62...
                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
                 │    └ <fastapi.applications.FastAPI object at 0x000001AFC4BEBD30>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x000001AFC8DDA470>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8E628C0>>
                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8E62...
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8E628C0>>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8E62...
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x000001AFC8E61240>
          └ <fastapi.applications.FastAPI object at 0x000001AFC4BEBD30>

> File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x000001AFC8E649D0>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8E62...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x000001AFC8E61210>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x000001AFC8E61240>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
          │                            │    │    │     │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x000001AFC8E649D0>
          │                            │    │    │     │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8E62...
          │                            │    │    │     └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │                            │    │    └ <starlette.requests.Request object at 0x000001AFC8E61E70>
          │                            │    └ <fastapi.routing.APIRouter object at 0x000001AFC8C8A890>
          │                            └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x000001AFC8E61210>
          └ <function wrap_app_handling_exceptions at 0x000001AFC790FAC0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001AFC8E64B80>
          │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8E62...
          │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          └ <fastapi.routing.APIRouter object at 0x000001AFC8C8A890>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001AFC8E64B80>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8E62...
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <bound method Router.app of <fastapi.routing.APIRouter object at 0x000001AFC8C8A890>>
          └ <fastapi.routing.APIRouter object at 0x000001AFC8C8A890>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001AFC8E64B80>
          │     │      │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8E62...
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │     └ <function Route.handle at 0x000001AFC7939000>
          └ APIRoute(path='/api/v1/meals/last', name='get_last_meal_by_user', methods=['GET'])

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001AFC8E64B80>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8E62...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <function request_response.<locals>.app at 0x000001AFC8CB8280>
          └ APIRoute(path='/api/v1/meals/last', name='get_last_meal_by_user', methods=['GET'])

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
          │                            │    │        │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001AFC8E64B80>
          │                            │    │        │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8E62...
          │                            │    │        └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │                            │    └ <starlette.requests.Request object at 0x000001AFC8E61BA0>
          │                            └ <function request_response.<locals>.app.<locals>.app at 0x000001AFC8E64C10>
          └ <function wrap_app_handling_exceptions at 0x000001AFC790FAC0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001AFC8E64CA0>
          │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8E62...
          │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          └ <function request_response.<locals>.app.<locals>.app at 0x000001AFC8E64C10>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
                     │ └ <starlette.requests.Request object at 0x000001AFC8E61BA0>
                     └ <function get_request_handler.<locals>.app at 0x000001AFC8CB8310>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x000001AFC793AB00>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {'user_id': '67fa8f895a7f4e0712d33d9b', 'db': AsyncIOMotorDatabase(Database(MongoClient(host=['localhost:27017'], document_cl...
                 │         └ <function get_last_meal_by_user at 0x000001AFC8C76EF0>
                 └ Dependant(path_params=[], query_params=[], header_params=[], cookie_params=[], body_params=[], dependencies=[Dependant(path_p...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\api\v1\meal.py", line 16, in get_last_meal_by_user
    return await get_last_meal_entry_by_user(db, user_id)
                 │                           │   └ '67fa8f895a7f4e0712d33d9b'
                 │                           └ AsyncIOMotorDatabase(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False, drive...
                 └ <function get_last_meal_entry_by_user at 0x000001AFC8C76C20>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\services\meal.py", line 15, in get_last_meal_entry_by_user
    logger.info(f"Last meal entry for user {user_id}: {meal.name}")
    │      └ <function Logger.info at 0x000001AFC8A9C550>
    └ <loguru.logger handlers=[(id=1, level=20, sink=<stdout>), (id=2, level=10, sink='logs/app.log')]>

AttributeError: 'dict' object has no attribute 'name'
2025-04-13 14:23:00.662 | INFO     | app.services.user:login_user:21 - User logged in: sammyscarface
2025-04-13 14:23:00.690 | ERROR    | __main__:global_exception_handler:28 - Unhandled exception: 'dict' object has no attribute 'name'
Traceback (most recent call last):

  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': None, '__package__': 'app', '__loader__': <_frozen_importlib_external.SourceFileLoader ob...
           │         └ <code object <module> at 0x000001AFC4BFE970, file "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\main.py", line 1>
           └ <function _run_code at 0x000001AFC4C0A4D0>

  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': None, '__package__': 'app', '__loader__': <_frozen_importlib_external.SourceFileLoader ob...
         └ <code object <module> at 0x000001AFC4BFE970, file "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\main.py", line 1>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\main.py", line 40, in <module>
    uvicorn.run(app, host="0.0.0.0", port=8000)
    │       │   └ <fastapi.applications.FastAPI object at 0x000001AFC4BEBD30>
    │       └ <function run at 0x000001AFC8D9F520>
    └ <module 'uvicorn' from 'C:\\Users\\ELITE SPACE FOOTBALL\\Documents\\mock_server\\.mock_server\\lib\\site-packages\\uvicorn\\_...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\uvicorn\main.py", line 579, in run
    server.run()
    │      └ <function Server.run at 0x000001AFC8D9EE60>
    └ <uvicorn.server.Server object at 0x000001AFC8DD9C00>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\uvicorn\server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x000001AFC8D9EEF0>
           │       │   └ <uvicorn.server.Server object at 0x000001AFC8DD9C00>
           │       └ <function run at 0x000001AFC505F6D0>
           └ <module 'asyncio' from 'C:\\Program Files\\Python310\\lib\\asyncio\\__init__.py'>

  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x000001AFC8D77840>
           │    └ <function BaseEventLoop.run_until_complete at 0x000001AFC6C72050>
           └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000001AFC6D21CF0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Program Files\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()

  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000001AFC6C73AC0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000001AFC6C17490>
    └ <Handle Task.task_wakeup(<Future finis...o Fio', ...}]>)>

  File "C:\Program Files\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finis...o Fio', ...}]>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finis...o Fio', ...}]>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finis...o Fio', ...}]>)>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x000001AFC8DDA470>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8FD9DB0>>
                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8FD9...
                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
                 │    └ <fastapi.applications.FastAPI object at 0x000001AFC4BEBD30>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x000001AFC8DDA470>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8FD9DB0>>
                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8FD9...
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8FD9DB0>>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8FD9...
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x000001AFC8E61240>
          └ <fastapi.applications.FastAPI object at 0x000001AFC4BEBD30>

> File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x000001AFC9222DD0>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8FD9...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x000001AFC8E61210>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x000001AFC8E61240>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
          │                            │    │    │     │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x000001AFC9222DD0>
          │                            │    │    │     │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8FD9...
          │                            │    │    │     └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │                            │    │    └ <starlette.requests.Request object at 0x000001AFC8FD9BD0>
          │                            │    └ <fastapi.routing.APIRouter object at 0x000001AFC8C8A890>
          │                            └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x000001AFC8E61210>
          └ <function wrap_app_handling_exceptions at 0x000001AFC790FAC0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001AFC9222E60>
          │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8FD9...
          │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          └ <fastapi.routing.APIRouter object at 0x000001AFC8C8A890>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001AFC9222E60>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8FD9...
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <bound method Router.app of <fastapi.routing.APIRouter object at 0x000001AFC8C8A890>>
          └ <fastapi.routing.APIRouter object at 0x000001AFC8C8A890>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001AFC9222E60>
          │     │      │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8FD9...
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │     └ <function Route.handle at 0x000001AFC7939000>
          └ APIRoute(path='/api/v1/meals/last', name='get_last_meal_by_user', methods=['GET'])

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001AFC9222E60>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8FD9...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <function request_response.<locals>.app at 0x000001AFC8CB8280>
          └ APIRoute(path='/api/v1/meals/last', name='get_last_meal_by_user', methods=['GET'])

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
          │                            │    │        │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001AFC9222E60>
          │                            │    │        │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8FD9...
          │                            │    │        └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │                            │    └ <starlette.requests.Request object at 0x000001AFC8FD9750>
          │                            └ <function request_response.<locals>.app.<locals>.app at 0x000001AFC9222F80>
          └ <function wrap_app_handling_exceptions at 0x000001AFC790FAC0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001AFC9223010>
          │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8FD9...
          │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          └ <function request_response.<locals>.app.<locals>.app at 0x000001AFC9222F80>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
                     │ └ <starlette.requests.Request object at 0x000001AFC8FD9750>
                     └ <function get_request_handler.<locals>.app at 0x000001AFC8CB8310>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x000001AFC793AB00>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {'user_id': '67fa8f895a7f4e0712d33d9b', 'db': AsyncIOMotorDatabase(Database(MongoClient(host=['localhost:27017'], document_cl...
                 │         └ <function get_last_meal_by_user at 0x000001AFC8C76EF0>
                 └ Dependant(path_params=[], query_params=[], header_params=[], cookie_params=[], body_params=[], dependencies=[Dependant(path_p...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\api\v1\meal.py", line 16, in get_last_meal_by_user
    return await get_last_meal_entry_by_user(db, user_id)
                 │                           │   └ '67fa8f895a7f4e0712d33d9b'
                 │                           └ AsyncIOMotorDatabase(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False, drive...
                 └ <function get_last_meal_entry_by_user at 0x000001AFC8C76C20>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\services\meal.py", line 15, in get_last_meal_entry_by_user
    logger.info(f"Last meal entry for user {user_id}: {meal.name}")
    │      └ <function Logger.info at 0x000001AFC8A9C550>
    └ <loguru.logger handlers=[(id=1, level=20, sink=<stdout>), (id=2, level=10, sink='logs/app.log')]>

AttributeError: 'dict' object has no attribute 'name'
2025-04-13 15:03:39.592 | INFO     | app.services.user:login_user:21 - User logged in: sammyscarface
2025-04-13 15:03:39.621 | ERROR    | __main__:global_exception_handler:28 - Unhandled exception: 'dict' object has no attribute 'name'
Traceback (most recent call last):

  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': None, '__package__': 'app', '__loader__': <_frozen_importlib_external.SourceFileLoader ob...
           │         └ <code object <module> at 0x000001AFC4BFE970, file "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\main.py", line 1>
           └ <function _run_code at 0x000001AFC4C0A4D0>

  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': None, '__package__': 'app', '__loader__': <_frozen_importlib_external.SourceFileLoader ob...
         └ <code object <module> at 0x000001AFC4BFE970, file "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\main.py", line 1>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\main.py", line 40, in <module>
    uvicorn.run(app, host="0.0.0.0", port=8000)
    │       │   └ <fastapi.applications.FastAPI object at 0x000001AFC4BEBD30>
    │       └ <function run at 0x000001AFC8D9F520>
    └ <module 'uvicorn' from 'C:\\Users\\ELITE SPACE FOOTBALL\\Documents\\mock_server\\.mock_server\\lib\\site-packages\\uvicorn\\_...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\uvicorn\main.py", line 579, in run
    server.run()
    │      └ <function Server.run at 0x000001AFC8D9EE60>
    └ <uvicorn.server.Server object at 0x000001AFC8DD9C00>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\uvicorn\server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x000001AFC8D9EEF0>
           │       │   └ <uvicorn.server.Server object at 0x000001AFC8DD9C00>
           │       └ <function run at 0x000001AFC505F6D0>
           └ <module 'asyncio' from 'C:\\Program Files\\Python310\\lib\\asyncio\\__init__.py'>

  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x000001AFC8D77840>
           │    └ <function BaseEventLoop.run_until_complete at 0x000001AFC6C72050>
           └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000001AFC6D21CF0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Program Files\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()

  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000001AFC6C73AC0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000001AFC6C17490>
    └ <Handle Task.task_wakeup(<Future finis...o Fio', ...}]>)>

  File "C:\Program Files\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finis...o Fio', ...}]>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finis...o Fio', ...}]>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finis...o Fio', ...}]>)>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x000001AFC8DDA470>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8EB2920>>
                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8EB2...
                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
                 │    └ <fastapi.applications.FastAPI object at 0x000001AFC4BEBD30>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x000001AFC8DDA470>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8EB2920>>
                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8EB2...
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8EB2920>>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8EB2...
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x000001AFC8E61240>
          └ <fastapi.applications.FastAPI object at 0x000001AFC4BEBD30>

> File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x000001AFC8FB8790>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8EB2...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x000001AFC8E61210>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x000001AFC8E61240>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
          │                            │    │    │     │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x000001AFC8FB8790>
          │                            │    │    │     │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8EB2...
          │                            │    │    │     └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │                            │    │    └ <starlette.requests.Request object at 0x000001AFC8EB2500>
          │                            │    └ <fastapi.routing.APIRouter object at 0x000001AFC8C8A890>
          │                            └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x000001AFC8E61210>
          └ <function wrap_app_handling_exceptions at 0x000001AFC790FAC0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001AFC8FB8700>
          │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8EB2...
          │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          └ <fastapi.routing.APIRouter object at 0x000001AFC8C8A890>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001AFC8FB8700>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8EB2...
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <bound method Router.app of <fastapi.routing.APIRouter object at 0x000001AFC8C8A890>>
          └ <fastapi.routing.APIRouter object at 0x000001AFC8C8A890>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001AFC8FB8700>
          │     │      │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8EB2...
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │     └ <function Route.handle at 0x000001AFC7939000>
          └ APIRoute(path='/api/v1/meals/last', name='get_last_meal_by_user', methods=['GET'])

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001AFC8FB8700>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8EB2...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <function request_response.<locals>.app at 0x000001AFC8CB8280>
          └ APIRoute(path='/api/v1/meals/last', name='get_last_meal_by_user', methods=['GET'])

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
          │                            │    │        │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001AFC8FB8700>
          │                            │    │        │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8EB2...
          │                            │    │        └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │                            │    └ <starlette.requests.Request object at 0x000001AFC8EB2560>
          │                            └ <function request_response.<locals>.app.<locals>.app at 0x000001AFC8FB85E0>
          └ <function wrap_app_handling_exceptions at 0x000001AFC790FAC0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001AFC8E64700>
          │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001AFC8EB2...
          │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          └ <function request_response.<locals>.app.<locals>.app at 0x000001AFC8FB85E0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
                     │ └ <starlette.requests.Request object at 0x000001AFC8EB2560>
                     └ <function get_request_handler.<locals>.app at 0x000001AFC8CB8310>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x000001AFC793AB00>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {'user_id': '67fa8f895a7f4e0712d33d9b', 'db': AsyncIOMotorDatabase(Database(MongoClient(host=['localhost:27017'], document_cl...
                 │         └ <function get_last_meal_by_user at 0x000001AFC8C76EF0>
                 └ Dependant(path_params=[], query_params=[], header_params=[], cookie_params=[], body_params=[], dependencies=[Dependant(path_p...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\api\v1\meal.py", line 16, in get_last_meal_by_user
    return await get_last_meal_entry_by_user(db, user_id)
                 │                           │   └ '67fa8f895a7f4e0712d33d9b'
                 │                           └ AsyncIOMotorDatabase(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False, drive...
                 └ <function get_last_meal_entry_by_user at 0x000001AFC8C76C20>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\services\meal.py", line 15, in get_last_meal_entry_by_user
    logger.info(f"Last meal entry for user {user_id}: {meal}")
    │      └ <function Logger.info at 0x000001AFC8A9C550>
    └ <loguru.logger handlers=[(id=1, level=20, sink=<stdout>), (id=2, level=10, sink='logs/app.log')]>

AttributeError: 'dict' object has no attribute 'name'
2025-04-13 15:25:32.867 | INFO     | __main__:lifespan:15 - Application startup completed
2025-04-13 15:26:13.973 | INFO     | app.services.user:login_user:21 - User logged in: sammyscarface
2025-04-13 15:26:14.054 | ERROR    | app.services.meal:get_last_meal_entry_by_user:37 - Validation error for meal data: 1 validation error for MealOut
id
  Field required [type=missing, input_value={'_id': ObjectId('67faa10...fa8f895a7f4e0712d33d9b'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-04-13 15:36:19.392 | INFO     | __main__:lifespan:20 - Application shutdown completed
2025-04-13 15:36:26.820 | INFO     | __main__:lifespan:15 - Application startup completed
2025-04-13 15:37:28.249 | INFO     | app.services.user:login_user:21 - User logged in: sammyscarface
2025-04-13 15:37:28.277 | ERROR    | app.services.meal:get_last_meal_entry_by_user:37 - Validation error for meal data: 1 validation error for MealOut
id
  Field required [type=missing, input_value={'_id': ObjectId('67faa10...fa8f895a7f4e0712d33d9b'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-04-13 15:42:55.597 | INFO     | app.services.user:login_user:21 - User logged in: sammyscarface
2025-04-13 15:42:55.629 | ERROR    | app.services.meal:get_last_meal_entry_by_user:37 - Validation error for meal data: 1 validation error for MealOut
id
  Field required [type=missing, input_value={'_id': ObjectId('67faa10...fa8f895a7f4e0712d33d9b'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-04-13 15:44:59.593 | ERROR    | app.services.meal:get_last_meal_entry_by_user:37 - Validation error for meal data: 1 validation error for MealOut
id
  Field required [type=missing, input_value={'_id': ObjectId('67fbbfd... 13, 13, 44, 55, 43000)}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-04-13 15:56:18.496 | INFO     | app.services.user:login_user:21 - User logged in: sammyscarface
2025-04-13 15:56:18.531 | ERROR    | app.services.meal:get_last_meal_entry_by_user:37 - Validation error for meal data: 1 validation error for MealOut
id
  Field required [type=missing, input_value={'_id': ObjectId('67fbbfd... 13, 13, 44, 55, 43000)}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-04-13 15:56:27.999 | ERROR    | app.services.meal:get_last_meal_entry_by_user:37 - Validation error for meal data: 1 validation error for MealOut
id
  Field required [type=missing, input_value={'_id': ObjectId('67fbbfd... 13, 13, 44, 55, 43000)}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-04-13 15:59:02.217 | INFO     | __main__:lifespan:20 - Application shutdown completed
2025-04-13 15:59:12.185 | INFO     | __main__:lifespan:15 - Application startup completed
2025-04-13 15:59:27.364 | INFO     | app.services.user:login_user:21 - User logged in: sammyscarface
2025-04-13 15:59:27.393 | ERROR    | app.services.meal:get_last_meal_entry_by_user:39 - Validation error for meal data: 1 validation error for MealOut
_id
  Field required [type=missing, input_value={'name': 'Fio Fio', 'desc...fbbfd7256565348992c0e3'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-04-13 16:14:38.118 | INFO     | __main__:lifespan:15 - Application startup completed
2025-04-13 16:16:29.682 | INFO     | app.services.user:login_user:21 - User logged in: sammyscarface
2025-04-13 16:16:29.714 | INFO     | app.services.meal:get_last_meal_entry_by_user:31 - Last meal entry for user 67fa8f895a7f4e0712d33d9b: Fio Fio
2025-04-13 16:20:34.501 | ERROR    | app.services.meal:create_meal_entry:22 - Validation error for meal data: 1 validation error for MealOut
_id
  Input should be a valid string [type=string_type, input_value=ObjectId('67fbc83258b9bae910e4582c'), input_type=ObjectId]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
2025-04-13 16:20:44.543 | INFO     | app.services.meal:get_last_meal_entry_by_user:31 - Last meal entry for user 67fa8f895a7f4e0712d33d9b: Jollof Rice
2025-04-13 16:21:38.068 | INFO     | __main__:lifespan:20 - Application shutdown completed
2025-04-13 21:57:29.915 | INFO     | __main__:lifespan:15 - Application startup completed
2025-04-13 21:58:50.960 | INFO     | app.services.user:login_user:21 - User logged in: sammyscarface
2025-04-13 21:58:51.004 | INFO     | app.services.meal:get_last_meal_entry_by_user:31 - Last meal entry for user 67fa8f895a7f4e0712d33d9b: Jollof Rice
2025-04-13 22:58:00.265 | INFO     | app.services.user:login_user:21 - User logged in: sammyscarface
2025-04-13 22:58:00.319 | INFO     | app.services.meal:get_last_meal_entry_by_user:31 - Last meal entry for user 67fa8f895a7f4e0712d33d9b: Jollof Rice
2025-04-13 23:04:25.356 | INFO     | app.services.user:login_user:21 - User logged in: sammyscarface
2025-04-13 23:04:25.384 | INFO     | app.services.meal:get_last_meal_entry_by_user:31 - Last meal entry for user 67fa8f895a7f4e0712d33d9b: Jollof Rice
2025-04-14 06:20:09.956 | INFO     | __main__:lifespan:15 - Application startup completed
2025-04-14 06:21:44.156 | INFO     | app.services.user:login_user:21 - User logged in: sammyscarface
2025-04-14 06:21:44.172 | INFO     | app.services.meal:get_last_meal_entry_by_user:32 - Last meal entry for user 67fa8f895a7f4e0712d33d9b: Jollof Rice
2025-04-14 06:22:18.422 | INFO     | app.services.meal:get_last_meal_entry_by_user:32 - Last meal entry for user 67fa8f895a7f4e0712d33d9b: Jollof Rice
2025-04-14 06:25:22.034 | INFO     | app.services.user:login_user:21 - User logged in: sammyscarface
2025-04-14 06:25:22.066 | INFO     | app.services.meal:get_last_meal_entry_by_user:32 - Last meal entry for user 67fa8f895a7f4e0712d33d9b: Jollof Rice
2025-04-14 06:27:00.093 | INFO     | app.services.user:login_user:21 - User logged in: sammyscarface
2025-04-14 06:27:00.125 | INFO     | app.services.meal:get_last_meal_entry_by_user:32 - Last meal entry for user 67fa8f895a7f4e0712d33d9b: Jollof Rice
2025-04-14 06:27:24.871 | INFO     | app.services.meal:get_last_meal_entry_by_user:32 - Last meal entry for user 67fa8f895a7f4e0712d33d9b: Jollof Rice
2025-04-14 06:31:23.555 | INFO     | app.services.user:login_user:21 - User logged in: sammyscarface
2025-04-14 06:31:23.583 | INFO     | app.services.meal:get_last_meal_entry_by_user:32 - Last meal entry for user 67fa8f895a7f4e0712d33d9b: Jollof Rice
2025-04-14 06:32:14.446 | INFO     | app.services.user:login_user:21 - User logged in: sammyscarface
2025-04-14 06:32:14.474 | INFO     | app.services.meal:get_last_meal_entry_by_user:32 - Last meal entry for user 67fa8f895a7f4e0712d33d9b: Jollof Rice
2025-04-14 08:34:46.595 | INFO     | app.services.user:login_user:21 - User logged in: sammyscarface
2025-04-14 08:34:46.664 | INFO     | app.services.meal:get_last_meal_entry_by_user:32 - Last meal entry for user 67fa8f895a7f4e0712d33d9b: Jollof Rice
2025-04-14 08:37:02.915 | INFO     | app.services.meal:get_last_meal_entry_by_user:32 - Last meal entry for user 67fa8f895a7f4e0712d33d9b: Jollof Rice
2025-04-14 08:40:29.009 | ERROR    | app.services.meal:create_meal_entry:23 - Validation error for meal data: 1 validation error for MealOut
_id
  Input should be a valid string [type=string_type, input_value=ObjectId('67fcaddc16df35129b6ad801'), input_type=ObjectId]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
2025-04-14 08:42:09.380 | ERROR    | app.services.meal:create_meal_entry:23 - Validation error for meal data: 1 validation error for MealOut
_id
  Input should be a valid string [type=string_type, input_value=ObjectId('67fcae4116df35129b6ad803'), input_type=ObjectId]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
2025-04-14 09:29:06.243 | INFO     | app.services.user:login_user:21 - User logged in: sammyscarface
2025-04-14 09:29:06.272 | INFO     | app.services.meal:get_last_meal_entry_by_user:32 - Last meal entry for user 67fa8f895a7f4e0712d33d9b: Custard and Moi Moi
2025-04-14 10:34:10.530 | INFO     | app.services.user:login_user:21 - User logged in: sammyscarface
2025-04-14 10:34:10.565 | INFO     | app.services.meal:get_last_meal_entry_by_user:32 - Last meal entry for user 67fa8f895a7f4e0712d33d9b: Custard and Moi Moi
2025-04-14 10:36:38.398 | INFO     | app.services.user:login_user:21 - User logged in: sammyscarface
2025-04-14 10:36:38.429 | INFO     | app.services.meal:get_last_meal_entry_by_user:32 - Last meal entry for user 67fa8f895a7f4e0712d33d9b: Custard and Moi Moi
2025-04-14 10:40:39.233 | INFO     | app.services.user:login_user:21 - User logged in: sammyscarface
2025-04-14 10:40:39.264 | INFO     | app.services.meal:get_last_meal_entry_by_user:32 - Last meal entry for user 67fa8f895a7f4e0712d33d9b: Custard and Moi Moi
2025-04-14 10:57:35.723 | INFO     | app.services.meal:get_last_meal_entry_by_user:32 - Last meal entry for user 67fa8f895a7f4e0712d33d9b: Custard and Moi Moi
2025-04-14 10:58:26.084 | INFO     | app.services.user:login_user:21 - User logged in: sammyscarface
2025-04-14 10:58:26.109 | INFO     | app.services.meal:get_last_meal_entry_by_user:32 - Last meal entry for user 67fa8f895a7f4e0712d33d9b: Custard and Moi Moi
2025-04-14 11:00:35.741 | INFO     | app.services.user:login_user:21 - User logged in: sammyscarface
2025-04-14 11:00:35.776 | INFO     | app.services.meal:get_last_meal_entry_by_user:32 - Last meal entry for user 67fa8f895a7f4e0712d33d9b: Custard and Moi Moi
2025-04-14 11:12:31.033 | INFO     | __main__:lifespan:15 - Application startup completed
2025-04-14 11:13:37.301 | INFO     | app.services.user:login_user:21 - User logged in: sammyscarface
2025-04-14 11:13:37.329 | ERROR    | app.services.meal:get_last_meal_entry_by_user:42 - Validation error for meal data: 1 validation error for MealListItem
ingredients.0.ingredient_id
  Field required [type=missing, input_value={'name': 'Custard', 'desc...'gram', 'quantity': 1.0}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-04-14 11:16:56.193 | INFO     | app.services.user:login_user:21 - User logged in: sammyscarface
2025-04-14 11:16:56.224 | ERROR    | app.services.meal:get_last_meal_entry_by_user:42 - Validation error for meal data: 1 validation error for MealListItem
ingredients.0.ingredient_id
  Field required [type=missing, input_value={'name': 'Custard', 'desc...'gram', 'quantity': 1.0}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-04-14 11:22:18.134 | INFO     | __main__:lifespan:20 - Application shutdown completed
2025-04-17 12:03:34.200 | INFO     | __main__:lifespan:15 - Application startup completed
2025-04-17 14:39:05.951 | ERROR    | __main__:global_exception_handler:28 - Unhandled exception: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 6800f64bbd62c66c59d20af9, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
Traceback (most recent call last):

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x0000020A60165360>>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x0000020A60165...
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x0000020A600CB280>
          └ <fastapi.applications.FastAPI object at 0x0000020A5BD4BD30>

> File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x0000020A600B51B0>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x0000020A60165...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x0000020A600CB250>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x0000020A600CB280>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
          │                            │    │    │     │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x0000020A600B51B0>
          │                            │    │    │     │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x0000020A60165...
          │                            │    │    │     └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │                            │    │    └ <starlette.requests.Request object at 0x0000020A600CBCA0>
          │                            │    └ <fastapi.routing.APIRouter object at 0x0000020A5FEEA9E0>
          │                            └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x0000020A600CB250>
          └ <function wrap_app_handling_exceptions at 0x0000020A5EB1FAC0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x0000020A600B5630>
          │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x0000020A60165...
          │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          └ <fastapi.routing.APIRouter object at 0x0000020A5FEEA9E0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x0000020A600B5630>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x0000020A60165...
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <bound method Router.app of <fastapi.routing.APIRouter object at 0x0000020A5FEEA9E0>>
          └ <fastapi.routing.APIRouter object at 0x0000020A5FEEA9E0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x0000020A600B5630>
          │     │      │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x0000020A60165...
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │     └ <function Route.handle at 0x0000020A5EB49000>
          └ APIRoute(path='/api/v1/users/login', name='login', methods=['POST'])

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x0000020A600B5630>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x0000020A60165...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <function request_response.<locals>.app at 0x0000020A5FF0C700>
          └ APIRoute(path='/api/v1/users/login', name='login', methods=['POST'])

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
          │                            │    │        │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x0000020A600B5630>
          │                            │    │        │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x0000020A60165...
          │                            │    │        └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │                            │    └ <starlette.requests.Request object at 0x0000020A60108880>
          │                            └ <function request_response.<locals>.app.<locals>.app at 0x0000020A600B5E10>
          └ <function wrap_app_handling_exceptions at 0x0000020A5EB1FAC0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x0000020A600B53F0>
          │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x0000020A60165...
          │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          └ <function request_response.<locals>.app.<locals>.app at 0x0000020A600B5E10>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
                     │ └ <starlette.requests.Request object at 0x0000020A60108880>
                     └ <function get_request_handler.<locals>.app at 0x0000020A5FF0C790>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x0000020A5EB4AB00>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {'db': AsyncIOMotorDatabase(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False...
                 │         └ <function login at 0x0000020A5FEDA5F0>
                 └ Dependant(path_params=[], query_params=[], header_params=[], cookie_params=[], body_params=[ModelField(field_info=Body(Pydant...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\api\v1\user.py", line 17, in login
    token = await login_user(db, user.username, user.password)
                  │          │   │    │         │    └ 'ghiblimeali'
                  │          │   │    │         └ UserLogin(username='sammyscarface', password='ghiblimeali')
                  │          │   │    └ 'sammyscarface'
                  │          │   └ UserLogin(username='sammyscarface', password='ghiblimeali')
                  │          └ AsyncIOMotorDatabase(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False, drive...
                  └ <function login_user at 0x0000020A5FC525F0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\services\user.py", line 16, in login_user
    user = await get_user_by_username(db, username)
                 │                    │   └ 'sammyscarface'
                 │                    └ AsyncIOMotorDatabase(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False, drive...
                 └ <function get_user_by_username at 0x0000020A5F8B5750>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\repositories\user.py", line 8, in get_user_by_username
    return await db.users.find_one({"username": username})
                 │                              └ 'sammyscarface'
                 └ AsyncIOMotorDatabase(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False, drive...

  File "C:\Program Files\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             │        │            └ None
             │        └ None
             └ None

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\pymongo\synchronous\collection.py", line 1755, in find_one
    for result in cursor.limit(-1):
                  │      └ <function Cursor.limit at 0x0000020A5F6F1240>
                  └ <pymongo.synchronous.cursor.Cursor object at 0x0000020A60165D20>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\pymongo\synchronous\cursor.py", line 1284, in __next__
    return self.next()
           │    └ <function Cursor.next at 0x0000020A5F6F24D0>
           └ <pymongo.synchronous.cursor.Cursor object at 0x0000020A60165D20>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\pymongo\synchronous\cursor.py", line 1260, in next
    if len(self._data) or self._refresh():
           │    │         │    └ <function Cursor._refresh at 0x0000020A5F6F23B0>
           │    │         └ <pymongo.synchronous.cursor.Cursor object at 0x0000020A60165D20>
           │    └ deque([])
           └ <pymongo.synchronous.cursor.Cursor object at 0x0000020A60165D20>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\pymongo\synchronous\cursor.py", line 1208, in _refresh
    self._send_message(q)
    │    │             └ <pymongo.message._Query object at 0x0000020A6016BED0>
    │    └ <function Cursor._send_message at 0x0000020A5F6F2320>
    └ <pymongo.synchronous.cursor.Cursor object at 0x0000020A60165D20>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\pymongo\synchronous\cursor.py", line 1102, in _send_message
    response = client._run_operation(
               │      └ <function MongoClient._run_operation at 0x0000020A5F7AE710>
               └ MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False, driver=DriverInfo(name='Motor', ver...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\pymongo\_csot.py", line 119, in csot_wrapper
    return func(self, *args, **kwargs)
           │    │      │       └ {'address': None}
           │    │      └ (<pymongo.message._Query object at 0x0000020A6016BED0>, <bound method Cursor._unpack_response of <pymongo.synchronous.cursor....
           │    └ MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False, driver=DriverInfo(name='Motor', ver...
           └ <function MongoClient._run_operation at 0x0000020A5F7AE680>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\pymongo\synchronous\mongo_client.py", line 1896, in _run_operation
    return self._retryable_read(
           │    └ <function MongoClient._retryable_read at 0x0000020A5F7AE950>
           └ MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False, driver=DriverInfo(name='Motor', ver...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\pymongo\synchronous\mongo_client.py", line 2005, in _retryable_read
    return self._retry_internal(
           │    └ <function MongoClient._retry_internal at 0x0000020A5F7AE8C0>
           └ MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False, driver=DriverInfo(name='Motor', ver...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\pymongo\_csot.py", line 119, in csot_wrapper
    return func(self, *args, **kwargs)
           │    │      │       └ {'is_read': True, 'address': None, 'read_pref': Primary(), 'retryable': True, 'operation_id': None}
           │    │      └ (<function MongoClient._run_operation.<locals>._cmd at 0x0000020A6024CE50>, <pymongo.synchronous.client_session.ClientSession...
           │    └ MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False, driver=DriverInfo(name='Motor', ver...
           └ <function MongoClient._retry_internal at 0x0000020A5F7AE830>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\pymongo\synchronous\mongo_client.py", line 1972, in _retry_internal
    ).run()

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\pymongo\synchronous\mongo_client.py", line 2709, in run
    return self._read() if self._is_read else self._write()
           │    │          │    │             │    └ <function _ClientConnectionRetryable._write at 0x0000020A5F7AFD00>
           │    │          │    │             └ <pymongo.synchronous.mongo_client._ClientConnectionRetryable object at 0x0000020A601660E0>
           │    │          │    └ True
           │    │          └ <pymongo.synchronous.mongo_client._ClientConnectionRetryable object at 0x0000020A601660E0>
           │    └ <function _ClientConnectionRetryable._read at 0x0000020A5F7AFD90>
           └ <pymongo.synchronous.mongo_client._ClientConnectionRetryable object at 0x0000020A601660E0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\pymongo\synchronous\mongo_client.py", line 2854, in _read
    self._server = self._get_server()
    │    │         │    └ <function _ClientConnectionRetryable._get_server at 0x0000020A5F7AFC70>
    │    │         └ <pymongo.synchronous.mongo_client._ClientConnectionRetryable object at 0x0000020A601660E0>
    │    └ None
    └ <pymongo.synchronous.mongo_client._ClientConnectionRetryable object at 0x0000020A601660E0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\pymongo\synchronous\mongo_client.py", line 2802, in _get_server
    return self._client._select_server(
           │    │       └ <function MongoClient._select_server at 0x0000020A5F7AE3B0>
           │    └ MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False, driver=DriverInfo(name='Motor', ver...
           └ <pymongo.synchronous.mongo_client._ClientConnectionRetryable object at 0x0000020A601660E0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\pymongo\synchronous\mongo_client.py", line 1791, in _select_server
    server = topology.select_server(
             │        └ <function Topology.select_server at 0x0000020A5F7971C0>
             └ <Topology <TopologyDescription id: 6800f64bbd62c66c59d20af9, topology_type: Unknown, servers: [<ServerDescription ('localhost...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\pymongo\synchronous\topology.py", line 409, in select_server
    server = self._select_server(
             │    └ <function Topology._select_server at 0x0000020A5F797130>
             └ <Topology <TopologyDescription id: 6800f64bbd62c66c59d20af9, topology_type: Unknown, servers: [<ServerDescription ('localhost...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\pymongo\synchronous\topology.py", line 387, in _select_server
    servers = self.select_servers(
              │    └ <function Topology.select_servers at 0x0000020A5F797010>
              └ <Topology <TopologyDescription id: 6800f64bbd62c66c59d20af9, topology_type: Unknown, servers: [<ServerDescription ('localhost...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\pymongo\synchronous\topology.py", line 294, in select_servers
    server_descriptions = self._select_servers_loop(
                          │    └ <function Topology._select_servers_loop at 0x0000020A5F7970A0>
                          └ <Topology <TopologyDescription id: 6800f64bbd62c66c59d20af9, topology_type: Unknown, servers: [<ServerDescription ('localhost...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\pymongo\synchronous\topology.py", line 344, in _select_servers_loop
    raise ServerSelectionTimeoutError(
          └ <class 'pymongo.errors.ServerSelectionTimeoutError'>

pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 6800f64bbd62c66c59d20af9, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
2025-04-17 14:40:32.694 | ERROR    | __main__:global_exception_handler:28 - Unhandled exception: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 6800f6a2bd62c66c59d20afa, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
Traceback (most recent call last):

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x0000020A60167820>>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x0000020A60167...
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x0000020A600CB280>
          └ <fastapi.applications.FastAPI object at 0x0000020A5BD4BD30>

> File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x0000020A600B5480>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x0000020A60167...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x0000020A600CB250>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x0000020A600CB280>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
          │                            │    │    │     │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x0000020A600B5480>
          │                            │    │    │     │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x0000020A60167...
          │                            │    │    │     └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │                            │    │    └ <starlette.requests.Request object at 0x0000020A60166DA0>
          │                            │    └ <fastapi.routing.APIRouter object at 0x0000020A5FEEA9E0>
          │                            └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x0000020A600CB250>
          └ <function wrap_app_handling_exceptions at 0x0000020A5EB1FAC0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x0000020A6024CF70>
          │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x0000020A60167...
          │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          └ <fastapi.routing.APIRouter object at 0x0000020A5FEEA9E0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x0000020A6024CF70>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x0000020A60167...
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <bound method Router.app of <fastapi.routing.APIRouter object at 0x0000020A5FEEA9E0>>
          └ <fastapi.routing.APIRouter object at 0x0000020A5FEEA9E0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x0000020A6024CF70>
          │     │      │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x0000020A60167...
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │     └ <function Route.handle at 0x0000020A5EB49000>
          └ APIRoute(path='/api/v1/users/login', name='login', methods=['POST'])

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x0000020A6024CF70>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x0000020A60167...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <function request_response.<locals>.app at 0x0000020A5FF0C700>
          └ APIRoute(path='/api/v1/users/login', name='login', methods=['POST'])

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
          │                            │    │        │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x0000020A6024CF70>
          │                            │    │        │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x0000020A60167...
          │                            │    │        └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │                            │    └ <starlette.requests.Request object at 0x0000020A601673A0>
          │                            └ <function request_response.<locals>.app.<locals>.app at 0x0000020A6024D000>
          └ <function wrap_app_handling_exceptions at 0x0000020A5EB1FAC0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x0000020A60538EE0>
          │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x0000020A60167...
          │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          └ <function request_response.<locals>.app.<locals>.app at 0x0000020A6024D000>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
                     │ └ <starlette.requests.Request object at 0x0000020A601673A0>
                     └ <function get_request_handler.<locals>.app at 0x0000020A5FF0C790>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x0000020A5EB4AB00>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {'db': AsyncIOMotorDatabase(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False...
                 │         └ <function login at 0x0000020A5FEDA5F0>
                 └ Dependant(path_params=[], query_params=[], header_params=[], cookie_params=[], body_params=[ModelField(field_info=Body(Pydant...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\api\v1\user.py", line 17, in login
    token = await login_user(db, user.username, user.password)
                  │          │   │    │         │    └ 'ghiblimeali'
                  │          │   │    │         └ UserLogin(username='sammyscarface', password='ghiblimeali')
                  │          │   │    └ 'sammyscarface'
                  │          │   └ UserLogin(username='sammyscarface', password='ghiblimeali')
                  │          └ AsyncIOMotorDatabase(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False, drive...
                  └ <function login_user at 0x0000020A5FC525F0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\services\user.py", line 16, in login_user
    user = await get_user_by_username(db, username)
                 │                    │   └ 'sammyscarface'
                 │                    └ AsyncIOMotorDatabase(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False, drive...
                 └ <function get_user_by_username at 0x0000020A5F8B5750>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\repositories\user.py", line 8, in get_user_by_username
    return await db.users.find_one({"username": username})
                 │                              └ 'sammyscarface'
                 └ AsyncIOMotorDatabase(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False, drive...

  File "C:\Program Files\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             │        │            └ None
             │        └ None
             └ None

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\pymongo\synchronous\collection.py", line 1755, in find_one
    for result in cursor.limit(-1):
                  │      └ <function Cursor.limit at 0x0000020A5F6F1240>
                  └ <pymongo.synchronous.cursor.Cursor object at 0x0000020A60167310>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\pymongo\synchronous\cursor.py", line 1284, in __next__
    return self.next()
           │    └ <function Cursor.next at 0x0000020A5F6F24D0>
           └ <pymongo.synchronous.cursor.Cursor object at 0x0000020A60167310>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\pymongo\synchronous\cursor.py", line 1260, in next
    if len(self._data) or self._refresh():
           │    │         │    └ <function Cursor._refresh at 0x0000020A5F6F23B0>
           │    │         └ <pymongo.synchronous.cursor.Cursor object at 0x0000020A60167310>
           │    └ deque([])
           └ <pymongo.synchronous.cursor.Cursor object at 0x0000020A60167310>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\pymongo\synchronous\cursor.py", line 1208, in _refresh
    self._send_message(q)
    │    │             └ <pymongo.message._Query object at 0x0000020A604EAF00>
    │    └ <function Cursor._send_message at 0x0000020A5F6F2320>
    └ <pymongo.synchronous.cursor.Cursor object at 0x0000020A60167310>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\pymongo\synchronous\cursor.py", line 1102, in _send_message
    response = client._run_operation(
               │      └ <function MongoClient._run_operation at 0x0000020A5F7AE710>
               └ MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False, driver=DriverInfo(name='Motor', ver...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\pymongo\_csot.py", line 119, in csot_wrapper
    return func(self, *args, **kwargs)
           │    │      │       └ {'address': None}
           │    │      └ (<pymongo.message._Query object at 0x0000020A604EAF00>, <bound method Cursor._unpack_response of <pymongo.synchronous.cursor....
           │    └ MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False, driver=DriverInfo(name='Motor', ver...
           └ <function MongoClient._run_operation at 0x0000020A5F7AE680>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\pymongo\synchronous\mongo_client.py", line 1896, in _run_operation
    return self._retryable_read(
           │    └ <function MongoClient._retryable_read at 0x0000020A5F7AE950>
           └ MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False, driver=DriverInfo(name='Motor', ver...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\pymongo\synchronous\mongo_client.py", line 2005, in _retryable_read
    return self._retry_internal(
           │    └ <function MongoClient._retry_internal at 0x0000020A5F7AE8C0>
           └ MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False, driver=DriverInfo(name='Motor', ver...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\pymongo\_csot.py", line 119, in csot_wrapper
    return func(self, *args, **kwargs)
           │    │      │       └ {'is_read': True, 'address': None, 'read_pref': Primary(), 'retryable': True, 'operation_id': None}
           │    │      └ (<function MongoClient._run_operation.<locals>._cmd at 0x0000020A605391B0>, <pymongo.synchronous.client_session.ClientSession...
           │    └ MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False, driver=DriverInfo(name='Motor', ver...
           └ <function MongoClient._retry_internal at 0x0000020A5F7AE830>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\pymongo\synchronous\mongo_client.py", line 1972, in _retry_internal
    ).run()

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\pymongo\synchronous\mongo_client.py", line 2709, in run
    return self._read() if self._is_read else self._write()
           │    │          │    │             │    └ <function _ClientConnectionRetryable._write at 0x0000020A5F7AFD00>
           │    │          │    │             └ <pymongo.synchronous.mongo_client._ClientConnectionRetryable object at 0x0000020A605441F0>
           │    │          │    └ True
           │    │          └ <pymongo.synchronous.mongo_client._ClientConnectionRetryable object at 0x0000020A605441F0>
           │    └ <function _ClientConnectionRetryable._read at 0x0000020A5F7AFD90>
           └ <pymongo.synchronous.mongo_client._ClientConnectionRetryable object at 0x0000020A605441F0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\pymongo\synchronous\mongo_client.py", line 2854, in _read
    self._server = self._get_server()
    │    │         │    └ <function _ClientConnectionRetryable._get_server at 0x0000020A5F7AFC70>
    │    │         └ <pymongo.synchronous.mongo_client._ClientConnectionRetryable object at 0x0000020A605441F0>
    │    └ None
    └ <pymongo.synchronous.mongo_client._ClientConnectionRetryable object at 0x0000020A605441F0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\pymongo\synchronous\mongo_client.py", line 2802, in _get_server
    return self._client._select_server(
           │    │       └ <function MongoClient._select_server at 0x0000020A5F7AE3B0>
           │    └ MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False, driver=DriverInfo(name='Motor', ver...
           └ <pymongo.synchronous.mongo_client._ClientConnectionRetryable object at 0x0000020A605441F0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\pymongo\synchronous\mongo_client.py", line 1791, in _select_server
    server = topology.select_server(
             │        └ <function Topology.select_server at 0x0000020A5F7971C0>
             └ <Topology <TopologyDescription id: 6800f6a2bd62c66c59d20afa, topology_type: Unknown, servers: [<ServerDescription ('localhost...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\pymongo\synchronous\topology.py", line 409, in select_server
    server = self._select_server(
             │    └ <function Topology._select_server at 0x0000020A5F797130>
             └ <Topology <TopologyDescription id: 6800f6a2bd62c66c59d20afa, topology_type: Unknown, servers: [<ServerDescription ('localhost...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\pymongo\synchronous\topology.py", line 387, in _select_server
    servers = self.select_servers(
              │    └ <function Topology.select_servers at 0x0000020A5F797010>
              └ <Topology <TopologyDescription id: 6800f6a2bd62c66c59d20afa, topology_type: Unknown, servers: [<ServerDescription ('localhost...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\pymongo\synchronous\topology.py", line 294, in select_servers
    server_descriptions = self._select_servers_loop(
                          │    └ <function Topology._select_servers_loop at 0x0000020A5F7970A0>
                          └ <Topology <TopologyDescription id: 6800f6a2bd62c66c59d20afa, topology_type: Unknown, servers: [<ServerDescription ('localhost...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\pymongo\synchronous\topology.py", line 344, in _select_servers_loop
    raise ServerSelectionTimeoutError(
          └ <class 'pymongo.errors.ServerSelectionTimeoutError'>

pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 6800f6a2bd62c66c59d20afa, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
2025-04-17 14:44:10.667 | INFO     | app.services.user:login_user:21 - User logged in: sammyscarface
2025-04-17 14:44:10.810 | ERROR    | app.services.meal:get_last_meal_entry_by_user:42 - Validation error for meal data: 1 validation error for MealListItem
ingredients.0.ingredient_id
  Field required [type=missing, input_value={'name': 'Custard', 'desc...'gram', 'quantity': 1.0}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-04-17 16:22:07.321 | INFO     | __main__:lifespan:20 - Application shutdown completed
2025-04-18 11:51:29.714 | INFO     | app.api.v1.user:register:12 - Registering user: testuser
2025-04-18 11:51:29.730 | INFO     | app.api.v1.user:register:12 - Registering user: testuser
2025-04-18 11:51:29.731 | ERROR    | app.main:global_exception_handler:31 - Unhandled exception: Username already exists
Traceback (most recent call last):

  File "C:\Program Files\Python310\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000001B0AAACD990>
    └ <Thread(Thread-2 (run_blocking_portal), started daemon 17364)>

  File "C:\Program Files\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000001B0AAACD6C0>
    └ <Thread(Thread-2 (run_blocking_portal), started daemon 17364)>

  File "C:\Program Files\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-2 (run_blocking_portal), started daemon 17364)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-2 (run_blocking_portal), started daemon 17364)>
    │    └ <function start_blocking_portal.<locals>.run_blocking_portal at 0x000001B0AE97FF40>
    └ <Thread(Thread-2 (run_blocking_portal), started daemon 17364)>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\anyio\from_thread.py", line 481, in run_blocking_portal
    _eventloop.run(
    │          └ <function run at 0x000001B0AB368DC0>
    └ <module 'anyio._core._eventloop' from 'C:\\Users\\ELITE SPACE FOOTBALL\\Documents\\mock_server\\.mock_server\\lib\\site-packa...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\anyio\_core\_eventloop.py", line 74, in run
    return async_backend.run(func, args, {}, backend_options)
           │             │   │     │         └ {}
           │             │   │     └ ()
           │             │   └ <function start_blocking_portal.<locals>.run_portal at 0x000001B0AE97FB50>
           │             └ <classmethod(<function AsyncIOBackend.run at 0x000001B0AFB4FE20>)>
           └ <class 'anyio._backends._asyncio.AsyncIOBackend'>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\anyio\_backends\_asyncio.py", line 2310, in run
    return runner.run(wrapper())
           │      │   └ <function start_blocking_portal.<locals>.run_portal at 0x000001B0AFB35480>
           │      └ <function Runner.run at 0x000001B0AFE05B40>
           └ <anyio._backends._asyncio.Runner object at 0x000001B0AFAFCD90>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\anyio\_backends\_asyncio.py", line 217, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='anyio.from_thread.start_blocking_portal.<locals>.run_portal' coro=<start_blocking_portal.<locals>.run_por...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x000001B0ACD193F0>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <anyio._backends._asyncio.Runner object at 0x000001B0AFAFCD90>

  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000001B0ACD6F7F0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Program Files\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()

  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000001B0ACD1AE60>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000001B0AB4CA830>
    └ <Handle Task.task_wakeup(<Future finis...al_tracker'))>)>

  File "C:\Program Files\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finis...al_tracker'))>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finis...al_tracker'))>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finis...al_tracker'))>)>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\anyio\from_thread.py", line 221, in _call_func
    retval = await retval_or_awaitable
                   └ <coroutine object FastAPI.__call__ at 0x000001B0AFB68190>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <function _TestClientTransport.handle_request.<locals>.send at 0x000001B0AE97CAF0>
                           │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x000001B0AE97F9A0>
                           └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/users/register', 'raw_path': b'/api/v1/users/regis...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <function _TestClientTransport.handle_request.<locals>.send at 0x000001B0AE97CAF0>
          │    │                │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x000001B0AE97F9A0>
          │    │                └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/users/register', 'raw_path': b'/api/v1/users/regis...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x000001B0AFB0A650>
          └ <fastapi.applications.FastAPI object at 0x000001B0AE050160>

> File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x000001B0AFD9BD90>
          │    │   │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x000001B0AE97F9A0>
          │    │   └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/users/register', 'raw_path': b'/api/v1/users/regis...
          │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x000001B0AFB0A620>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x000001B0AFB0A650>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
          │                            │    │    │     │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x000001B0AFD9BD90>
          │                            │    │    │     │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x000001B0AE97F9A0>
          │                            │    │    │     └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/users/register', 'raw_path': b'/api/v1/users/regis...
          │                            │    │    └ <starlette.requests.Request object at 0x000001B0AFAFC100>
          │                            │    └ <fastapi.routing.APIRouter object at 0x000001B0AE94BAC0>
          │                            └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x000001B0AFB0A620>
          └ <function wrap_app_handling_exceptions at 0x000001B0ADD8AE60>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001B0AFE4C0D0>
          │   │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x000001B0AE97F9A0>
          │   └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/users/register', 'raw_path': b'/api/v1/users/regis...
          └ <fastapi.routing.APIRouter object at 0x000001B0AE94BAC0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001B0AFE4C0D0>
          │    │                │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x000001B0AE97F9A0>
          │    │                └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/users/register', 'raw_path': b'/api/v1/users/regis...
          │    └ <bound method Router.app of <fastapi.routing.APIRouter object at 0x000001B0AE94BAC0>>
          └ <fastapi.routing.APIRouter object at 0x000001B0AE94BAC0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001B0AFE4C0D0>
          │     │      │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x000001B0AE97F9A0>
          │     │      └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/users/register', 'raw_path': b'/api/v1/users/regis...
          │     └ <function Route.handle at 0x000001B0ADDA83A0>
          └ APIRoute(path='/api/v1/users/register', name='register', methods=['POST'])

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001B0AFE4C0D0>
          │    │   │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x000001B0AE97F9A0>
          │    │   └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/users/register', 'raw_path': b'/api/v1/users/regis...
          │    └ <function request_response.<locals>.app at 0x000001B0AE91E7A0>
          └ APIRoute(path='/api/v1/users/register', name='register', methods=['POST'])

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
          │                            │    │        │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001B0AFE4C0D0>
          │                            │    │        │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x000001B0AE97F9A0>
          │                            │    │        └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/users/register', 'raw_path': b'/api/v1/users/regis...
          │                            │    └ <starlette.requests.Request object at 0x000001B0AFAFC160>
          │                            └ <function request_response.<locals>.app.<locals>.app at 0x000001B0AFE4C160>
          └ <function wrap_app_handling_exceptions at 0x000001B0ADD8AE60>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001B0AFE4C1F0>
          │   │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x000001B0AE97F9A0>
          │   └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/users/register', 'raw_path': b'/api/v1/users/regis...
          └ <function request_response.<locals>.app.<locals>.app at 0x000001B0AFE4C160>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
                     │ └ <starlette.requests.Request object at 0x000001B0AFAFC160>
                     └ <function get_request_handler.<locals>.app at 0x000001B0AE91E4D0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x000001B0ADDA9EA0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {'db': AsyncIOMotorDatabase(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False...
                 │         └ <function register at 0x000001B0AE91C550>
                 └ Dependant(path_params=[], query_params=[], header_params=[], cookie_params=[], body_params=[ModelField(field_info=Body(Pydant...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\api\v1\user.py", line 13, in register
    return await register_user(db, user)
                 │             │   └ UserCreate(username='testuser', email='test@example.com', password='securepassword123')
                 │             └ AsyncIOMotorDatabase(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False, drive...
                 └ <AsyncMock name='register_user' id='1858373459424'>

  File "C:\Program Files\Python310\lib\unittest\mock.py", line 2202, in _execute_mock_call
    raise effect
          └ UserCreationError('Username already exists')

app.exceptions.user.UserCreationError: Username already exists
2025-04-18 11:51:31.436 | ERROR    | app.main:global_exception_handler:31 - Unhandled exception: Invalid credentials
Traceback (most recent call last):

  File "C:\Program Files\Python310\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000001B0AAACD990>
    └ <Thread(Thread-5 (run_blocking_portal), started daemon 12224)>

  File "C:\Program Files\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000001B0AAACD6C0>
    └ <Thread(Thread-5 (run_blocking_portal), started daemon 12224)>

  File "C:\Program Files\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-5 (run_blocking_portal), started daemon 12224)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-5 (run_blocking_portal), started daemon 12224)>
    │    └ <function start_blocking_portal.<locals>.run_blocking_portal at 0x000001B0AFE04310>
    └ <Thread(Thread-5 (run_blocking_portal), started daemon 12224)>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\anyio\from_thread.py", line 481, in run_blocking_portal
    _eventloop.run(
    │          └ <function run at 0x000001B0AB368DC0>
    └ <module 'anyio._core._eventloop' from 'C:\\Users\\ELITE SPACE FOOTBALL\\Documents\\mock_server\\.mock_server\\lib\\site-packa...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\anyio\_core\_eventloop.py", line 74, in run
    return async_backend.run(func, args, {}, backend_options)
           │             │   │     │         └ {}
           │             │   │     └ ()
           │             │   └ <function start_blocking_portal.<locals>.run_portal at 0x000001B0AFE04040>
           │             └ <classmethod(<function AsyncIOBackend.run at 0x000001B0AFB4FE20>)>
           └ <class 'anyio._backends._asyncio.AsyncIOBackend'>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\anyio\_backends\_asyncio.py", line 2310, in run
    return runner.run(wrapper())
           │      │   └ <function start_blocking_portal.<locals>.run_portal at 0x000001B0AFE04D30>
           │      └ <function Runner.run at 0x000001B0AFE05B40>
           └ <anyio._backends._asyncio.Runner object at 0x000001B0B01FA500>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\anyio\_backends\_asyncio.py", line 217, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='anyio.from_thread.start_blocking_portal.<locals>.run_portal' coro=<start_blocking_portal.<locals>.run_por...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x000001B0ACD193F0>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <anyio._backends._asyncio.Runner object at 0x000001B0B01FA500>

  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000001B0ACD6F7F0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Program Files\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()

  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000001B0ACD1AE60>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000001B0AB4CA830>
    └ <Handle Task.task_wakeup(<Future finis...al_tracker'))>)>

  File "C:\Program Files\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finis...al_tracker'))>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finis...al_tracker'))>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finis...al_tracker'))>)>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\anyio\from_thread.py", line 221, in _call_func
    retval = await retval_or_awaitable
                   └ <coroutine object FastAPI.__call__ at 0x000001B0AFF7DD90>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <function _TestClientTransport.handle_request.<locals>.send at 0x000001B0AE97C820>
                           │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x000001B0AE97CA60>
                           └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/users/login', 'raw_path': b'/api/v1/users/login', ...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <function _TestClientTransport.handle_request.<locals>.send at 0x000001B0AE97C820>
          │    │                │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x000001B0AE97CA60>
          │    │                └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/users/login', 'raw_path': b'/api/v1/users/login', ...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x000001B0AFB0A650>
          └ <fastapi.applications.FastAPI object at 0x000001B0AE050160>

> File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x000001B0AFE04790>
          │    │   │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x000001B0AE97CA60>
          │    │   └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/users/login', 'raw_path': b'/api/v1/users/login', ...
          │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x000001B0AFB0A620>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x000001B0AFB0A650>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
          │                            │    │    │     │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x000001B0AFE04790>
          │                            │    │    │     │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x000001B0AE97CA60>
          │                            │    │    │     └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/users/login', 'raw_path': b'/api/v1/users/login', ...
          │                            │    │    └ <starlette.requests.Request object at 0x000001B0B01FB370>
          │                            │    └ <fastapi.routing.APIRouter object at 0x000001B0AE94BAC0>
          │                            └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x000001B0AFB0A620>
          └ <function wrap_app_handling_exceptions at 0x000001B0ADD8AE60>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001B0AFE04E50>
          │   │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x000001B0AE97CA60>
          │   └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/users/login', 'raw_path': b'/api/v1/users/login', ...
          └ <fastapi.routing.APIRouter object at 0x000001B0AE94BAC0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001B0AFE04E50>
          │    │                │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x000001B0AE97CA60>
          │    │                └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/users/login', 'raw_path': b'/api/v1/users/login', ...
          │    └ <bound method Router.app of <fastapi.routing.APIRouter object at 0x000001B0AE94BAC0>>
          └ <fastapi.routing.APIRouter object at 0x000001B0AE94BAC0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001B0AFE04E50>
          │     │      │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x000001B0AE97CA60>
          │     │      └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/users/login', 'raw_path': b'/api/v1/users/login', ...
          │     └ <function Route.handle at 0x000001B0ADDA83A0>
          └ APIRoute(path='/api/v1/users/login', name='login', methods=['POST'])

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001B0AFE04E50>
          │    │   │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x000001B0AE97CA60>
          │    │   └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/users/login', 'raw_path': b'/api/v1/users/login', ...
          │    └ <function request_response.<locals>.app at 0x000001B0AE91E830>
          └ APIRoute(path='/api/v1/users/login', name='login', methods=['POST'])

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
          │                            │    │        │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001B0AFE04E50>
          │                            │    │        │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x000001B0AE97CA60>
          │                            │    │        └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/users/login', 'raw_path': b'/api/v1/users/login', ...
          │                            │    └ <starlette.requests.Request object at 0x000001B0B01FB7F0>
          │                            └ <function request_response.<locals>.app.<locals>.app at 0x000001B0AFB35480>
          └ <function wrap_app_handling_exceptions at 0x000001B0ADD8AE60>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001B0AFB356C0>
          │   │      └ <function _TestClientTransport.handle_request.<locals>.receive at 0x000001B0AE97CA60>
          │   └ {'type': 'http', 'http_version': '1.1', 'method': 'POST', 'path': '/api/v1/users/login', 'raw_path': b'/api/v1/users/login', ...
          └ <function request_response.<locals>.app.<locals>.app at 0x000001B0AFB35480>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
                     │ └ <starlette.requests.Request object at 0x000001B0B01FB7F0>
                     └ <function get_request_handler.<locals>.app at 0x000001B0AE91E8C0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x000001B0ADDA9EA0>

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\.mock_server\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {'db': AsyncIOMotorDatabase(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False...
                 │         └ <function login at 0x000001B0AE91C670>
                 └ Dependant(path_params=[], query_params=[], header_params=[], cookie_params=[], body_params=[ModelField(field_info=Body(Pydant...

  File "C:\Users\ELITE SPACE FOOTBALL\Documents\mock_server\app\api\v1\user.py", line 17, in login
    token = await login_user(db, user.username, user.password)
                  │          │   │    │         │    └ 'wrongpassword'
                  │          │   │    │         └ UserLogin(username='wronguser', password='wrongpassword')
                  │          │   │    └ 'wronguser'
                  │          │   └ UserLogin(username='wronguser', password='wrongpassword')
                  │          └ AsyncIOMotorDatabase(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=False, drive...
                  └ <AsyncMock name='login_user' id='1858373413152'>

  File "C:\Program Files\Python310\lib\unittest\mock.py", line 2202, in _execute_mock_call
    raise effect
          └ UserNotFoundError('Invalid credentials')

app.exceptions.user.UserNotFoundError: Invalid credentials
2025-04-18 11:51:31.849 | INFO     | app.services.user:register_user:12 - User registered: testuser
2025-04-18 11:51:31.857 | INFO     | app.services.user:login_user:21 - User logged in: testuser
2025-04-18 11:51:31.869 | WARNING  | app.services.user:login_user:18 - Login failed for username: nonexistent
2025-04-18 11:51:31.881 | WARNING  | app.services.user:login_user:18 - Login failed for username: testuser
2025-04-18 12:30:59.699 | INFO     | app.api.v1.user:register:12 - Registering user: testuser
2025-04-18 12:30:59.743 | INFO     | app.api.v1.user:register:12 - Registering user: testuser
2025-04-18 12:30:59.801 | INFO     | app.services.user:register_user:12 - User registered: testuser
2025-04-18 12:30:59.814 | INFO     | app.services.user:login_user:21 - User logged in: testuser
2025-04-18 12:30:59.823 | WARNING  | app.services.user:login_user:18 - Login failed for username: nonexistent
2025-04-18 12:30:59.833 | WARNING  | app.services.user:login_user:18 - Login failed for username: testuser
2025-04-18 21:22:24.587 | INFO     | app.services.meal:get_last_meal_entry_by_user:66 - Last meal entry for user test_user_123: Breakfast
2025-04-18 23:06:22.675 | INFO     | app.services.meal:get_last_meal_entry_by_user:66 - Last meal entry for user test_user_id: Breakfast
2025-04-19 00:29:39.178 | INFO     | app.services.meal:get_last_meal_entry_by_user:65 - Last meal entry for user test_user_123: Breakfast
2025-04-19 00:35:17.502 | INFO     | app.services.meal:get_last_meal_entry_by_user:65 - Last meal entry for user test_user_123: Breakfast
